# Generated by Django 4.0.6 on 2022-07-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decription', models.TextField(default='-')),
                ('creation_date', models.DateField(auto_now=True)),
                ('importance', models.CharField(choices=[('High', "It's important"), ('Common', 'Common task'), ('Low', 'Just trifle')], max_length=100)),
                ('deadline', models.DateField()),
            ],
        ),
    ]
